export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_HOMEPAGE_ARTICLES_SUCCESS = 'LOAD_HOMEPAGE_ARTICLES_SUCCESS';
export const LOAD_SOURCES_SUCCESS = 'LOAD_SOURCES_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
